# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ruben Cunha
email: ruben dot cunha at gmail dot com
description: >
  Frontend developer based in Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rgcunha84
github_username:  rgcunha

# Build settings
markdown: kramdown

include: ['_pages']
